### ISSUE TITLE
Error on generating - timeout

### ISSUE THREAD

**Issue by ignatandrei** [jean-humann/docs-to-pdf#236]
I am trying to generate PDF from 

```
npx docs-to-pdf --initialDocURLs="https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG" --contentSelector="article" --paginationSelector="a.pagination-nav__link.pagination-nav__link--next" --excludeSelectors=".margin-vert--xl a,[class^='tocCollapsible'],.breadcrumbs,.theme-edit-this-page"  --coverTitle="RSCG --protocolTimeout=54000"
```

It is all well before the final   
[30.08.2023 23:15.27.852] [LOG]   Start generating PDF...
[30.08.2023 23:15.27.852] [LOG]   Generate cover...
[30.08.2023 23:15.27.852] [LOG]   Start generating TOC...
[30.08.2023 23:15.27.958] [LOG]   Restructuring the html of a document...
[30.08.2023 23:15.35.378] [LOG]   Remove unnecessary HTML...
[30.08.2023 23:15.35.379] [LOG]   Scroll to the bottom of the page...
[30.08.2023 23:16.29.393] [ERROR] ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
 at <instance_members_initializer> (C:\Users\ignat\AppData\Local\npm-cache\_npx\c16ac64a6c7aba73\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:49:14)
    at new Callback (C:\Users\ignat\AppData\Local\npm-cache\_npx\c16ac64a6c7aba73\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:53:16)
    at CallbackRegistry.create (C:\Users\ignat\AppData\Local\npm-cache\_npx\c16ac64a6c7aba73\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:93:26)

Could you please help?

**Comment by ignatandrei** [comment]
Modified to 1080000
